PICO_PROJECT/PICO_PROJECT/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from . import views
from core.views import ProfileView, ChargeView, MyPicoLog
from core.views import follow, FollowersView, FollowingView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.register, name='register'),
    re_path(r'^accounts/register/activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),

    path('', views.HomeView.as_view(), name='home'),
    path('explore/', include('photo.urls')),
    path('charge/', ChargeView.as_view(), name='charge'),
    path('search/', views.post_search, name='search'),
    path('log/user/<str:username>', MyPicoLog.as_view(), name='mypicolog'),
    # path('log/photo/<int:pk>', name='photopicolog'),
    path('<str:username>/', ProfileView.as_view(), name='profile'),
    path('<str:username>/follow/', follow, name='follow'),
    path('<str:username>/followers', FollowersView.as_view(), name='followers'),
    path('<str:username>/following', FollowingView.as_view(), name='following'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PICO_PROJECT/photo/urls.py
from django.urls import path
from . import views

app_name = 'photo'
urlpatterns = [
    # 기본 explore은 day의 rank와 같다.
    path('', views.PhotoLV.as_view(), name='index'),

    path('day', views.PhotoLVRankDay.as_view(), name='rank_day'),
    path('week/', views.PhotoLVRankWeek.as_view(), name='rank_week'),
    path('month/', views.PhotoLVRankMonth.as_view(), name='rank_month'),
    path('3month/', views.PhotoLVRank3Month.as_view(), name='rank_3month'),
    path('year/', views.PhotoLVRankYear.as_view(), name='rank_year'),
    path('all/', views.PhotoLVRankAll.as_view(), name='rank_all'),

    path('follow/', views.PhotoFollowView.as_view(), name='follow'),
    path('<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    path('add/', views.PhotoCV.as_view(), name='photo_add'),
    path('change/', views.PhotoChangeLV.as_view(), name='photo_change'),
    path('<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),
    path('<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),

    path('<int:pk>/donate', views.PhotoDonateDetailView.as_view(), name='photo_donate'),
    path('<int:pk>/log', views. PhotoPicoLog.as_view(), name='photo_pico_log'),

    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
] 

PICO_PROJECT/templates/base.html
<!-- 
<!DOCTYPE html>
<html lang="ko">
<body style="padding-top:70px; color: #eee; background-color: #222; margin: auto; font-family: 'Lucida Grande', Verdana, Arial, sans-serif;">
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg fixed-top">
      <span class="navbar-brand mx-5 mb-0 font-weight-bold">PICO PROJECT</span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item btn btn-dark mx-1">
            <a class="nav-link" href="{% url 'home' %}">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown btn btn-dark mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Explore
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'photo:index' %}">New</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'photo:rank_day' %}">Day</a>
                <a class="dropdown-item" href="{% url 'photo:rank_week' %}">Week</a>
                <a class="dropdown-item" href="{% url 'photo:rank_month' %}">Month</a>
                <a class="dropdown-item" href="{% url 'photo:rank_3month' %}">3Month</a>
                <a class="dropdown-item" href="{% url 'photo:rank_year' %}">Year</a>
                <a class="dropdown-item" href="{% url 'photo:rank_all' %}">All</a>
              </div>
          </li>
          <li class="nav-item btn btn-dark mx-1">
            <a class="nav-link" href="{% url 'photo:follow' %}">Following<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown btn btn-dark mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Util
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                <div class="dropdown-divider"></div>
                
              </div>
          </li>

          <li class="nav-item dropdown btn btn-dark mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Add
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a href="{% url 'photo:photo_add' %}" class="dropdown-item">Photo</a>
              </div>
          </li>

          <li class="nav-item dropdown btn btn-dark mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Change
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a href="{% url 'photo:photo_change' %}" class="dropdown-item">Photo</a>
              </div>
          </li>

        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="GET">
          {% csrf_token %}
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search_word" value="{{ search_word }}" required>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item dropdown mx-1 btn btn-dark">
            {% if user.is_active %}
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown"><i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a>
            <div class="dropdown-menu">
              <a href="{% url 'profile' user.get_username %}" class="dropdown-item">Profile</a>
              <a href="{% url 'logout' %}" class="dropdown-item">Logout</a>
              <a href="{% url 'password_change' %}" class="dropdown-item">Change Password</a>
            </div>
            {% else %}
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fas fa-user"></i>&ensp;Anonymous&ensp;</a>
            <div class="dropdown-menu">
              <a href="{% url 'login' %}" class="dropdown-item">Login</a>
              <a href="{% url 'register' %}" class="dropdown-item">Register</a>
            </div>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      
    </div>
    {% block footer %}{% endblock %}
  </body>
</html> -->






{% load static %}
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
    <noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
    {% block extra-style %}{% endblock %}
    {% block extra-script %}{% endblock %}
  </head>
	<body class="is-preload">
		<div id="page-wrapper">
    <!-- Header -->
      <header id="header">
        <h1 id="logo"><a href="{% url 'home' %}">PICO</a></h1>
        <nav id="nav">
          <ul>
            <li>
              <form action="{% url 'search' %}" method="GET">
                {% csrf_token %}
                <input type="search" placeholder="Search" aria-label="Search" name="search_word" value="{{ search_word }}" required>
              </form>
            </li> 
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'photo:index' %}">Rank</a></li>
            <li><a href="{% url 'photo:follow' %}">Following</a></li>
            {% if user.is_active %}
              <li><a href="{% url 'profile' user.get_username %}"><i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a></li>
              <li><a href="{% url 'logout' %}" class="button primary">Sign out</a></li>
            {% else %}
              <li><a href="{% url 'login' %}" class="button primary">Sign In</a></li>
            {% endif %}
          </ul>
        </nav>
      </header>

    <!-- Main -->
      <div id="main" class="wrapper style1">
        <div class="container">
          {% block content %}{% endblock %}
        </div>
      </div>

    <!-- Footer -->
      <footer id="footer">
        <ul class="icons">
          <li><a href="#" class="icon brands alt fa-twitter"><span class="label">Twitter</span></a></li>
          <li><a href="#" class="icon brands alt fa-facebook-f"><span class="label">Facebook</span></a></li>
          <li><a href="#" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
          <li><a href="#" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
        </ul>
        <ul class="copyright">
          <li>&copy; PICO_3KIM All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
        </ul>
      </footer>
    </div>
  <!-- Scripts -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.dropotron.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
    <script src="{% static 'assets/js/browser.min.js' %}"></script>
    <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
    <script src="{% static 'assets/js/util.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
	</body>
</html>

PICO_PROJECT/templates/charge.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}{{ request.user.username }} charge{% endblock %}
{% block content %}
<h1>{{ request.user.username }}</h1>
<div>
    You have PICOIN => {{ user.profile.PICOIN }}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_table }}
    </form>
</div>
<br>
{% endblock %}

PICO_PROJECT/templates/home.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>PICO</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<script src="http://code.jquery.com/jquery-latest.min.js"></script>
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">
		<div id="page-wrapper">

			<!-- Header -->
      <header id="header">
        <h1 id="logo"><a href="{% url 'home' %}">PICO</a></h1>
        <nav id="nav">
          <ul>
			<li>
				<form action="{% url 'search' %}" method="GET">
				  {% csrf_token %}
				  <input type="search" placeholder="Search" aria-label="Search" name="search_word" value="{{ search_word }}" required>
				</form>
			</li> 
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'photo:index' %}">Rank</a></li>
			<li><a href="{% url 'photo:follow' %}">Following</a></li>      
            {% if user.is_active %}
              <li><a href="{% url 'profile' user.get_username %}"><i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a></li>
			  <li><a href="{% url 'logout' %}" class="button primary">Sign out</a></li>
			  {% else %}
              <li><a href="{% url 'login' %}" class="button primary">Sign In</a></li>
            {% endif %}
          </ul>
        </nav>
      </header>

			<!-- Banner -->
				<section id="banner">
					<div class="content">
						<header>
							<h2>The future has landed</h2>
							<p>And there are no hoverboards or flying cars.<br />
							Just apps. Lots of mother flipping apps.</p>
						</header>
					</div>
					<a href="#one" class="goto-next scrolly">Next</a>
				</section>

			<!-- One -->
				<section id="one" class="spotlight style1 bottom">
					<span class="image fit main"><img src="{% static 'images/firework.png' %}" alt="" /></span>
					<div class="content">
						<div class="container">
							<div class="row">
								<div class="col-4 col-12-medium">
									<header>
										<h2>Odio faucibus ipsum integer consequat</h2>
										<p>Nascetur eu nibh vestibulum amet gravida nascetur praesent</p>
									</header>
								</div>
								<div class="col-4 col-12-medium">
									<p>Feugiat accumsan lorem eu ac lorem amet sed accumsan donec.
									Blandit orci porttitor semper. Arcu phasellus tortor enim mi
									nisi praesent dolor adipiscing. Integer mi sed nascetur cep aliquet
									augue varius tempus lobortis porttitor accumsan consequat
									adipiscing lorem dolor.</p>
								</div>
								<div class="col-4 col-12-medium">
									<p>Morbi enim nascetur et placerat lorem sed iaculis neque ante
									adipiscing adipiscing metus massa. Blandit orci porttitor semper.
									Arcu phasellus tortor enim mi mi nisi praesent adipiscing. Integer
									mi sed nascetur cep aliquet augue varius tempus. Feugiat lorem
									ipsum dolor nullam.</p>
								</div>
							</div>
						</div>
					</div>
					<a href="#two" class="goto-next scrolly">Next</a>
				</section>

			<!-- Two -->
				<section id="two" class="spotlight style2 right">
					<span class="image fit main"><img src="{% static 'images/firework2.jpg' %}" alt="" /></span>
					<div class="content">
						<header>
							<h2>Interdum amet non magna accumsan</h2>
							<p>Nunc commodo accumsan eget id nisi eu col volutpat magna</p>
						</header>
						<p>Feugiat accumsan lorem eu ac lorem amet ac arcu phasellus tortor enim mi mi nisi praesent adipiscing. Integer mi sed nascetur cep aliquet augue varius tempus lobortis porttitor lorem et accumsan consequat adipiscing lorem.</p>
						<ul class="actions">
							<li><a href="{% url 'photo:index' %}" class="button">Learn More</a></li>
						</ul>
					</div>
					<a href="#three" class="goto-next scrolly">Next</a>
				</section>

			<!-- Three -->
				<section id="three" class="spotlight style3 left">
					<span class="image fit main bottom"><img src="{% static 'images/firework3.jpg' %}" alt="" /></span>
					<div class="content">
						<header>
							<h2>Interdum felis blandit praesent sed augue</h2>
							<p>Accumsan integer ultricies aliquam vel massa sapien phasellus</p>
						</header>
						<p>Feugiat accumsan lorem eu ac lorem amet ac arcu phasellus tortor enim mi mi nisi praesent adipiscing. Integer mi sed nascetur cep aliquet augue varius tempus lobortis porttitor lorem et accumsan consequat adipiscing lorem.</p>
						<ul class="actions">
							<li><a href="{% url 'photo:follow' %}" class="button">Learn More</a></li>
						</ul>
					</div>
				</section>
			<!-- Footer -->
      <footer id="footer">
        <ul class="icons">
          <li><a href="#" class="icon brands alt fa-twitter"><span class="label">Twitter</span></a></li>
          <li><a href="#" class="icon brands alt fa-facebook-f"><span class="label">Facebook</span></a></li>
          <li><a href="#" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
          <li><a href="#" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
        </ul>
        <ul class="copyright">
          <li>&copy; PICO_3KIM All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
        </ul>
      </footer>
    </div>

		<!-- Scripts -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.dropotron.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrollex.min.js' %}"></script>
    <script src="{% static 'assets/js/browser.min.js' %}"></script>
    <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
    <script src="{% static 'assets/js/util.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>

	</body>
</html>

PICO_PROJECT/templates/mypicolog.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}picolog_list.html{% endblock %}
{% block content %}
<h1>PICO - LOG [{{ request.user.username }}]</h1>

<br>
<table class="table table-bordered table-condensed table-striped">
    <thead>
        <tr class="table-primary">
            <th>누가</th>
            <th>얼마나</th>
            <th>어떻게</th>
            <th>언제</th>
        </tr>
    </thead>
    <tbody>
        {% for item in object_list %}
        <tr class="table-secondary">
            <td><a href="{% url 'profile' item.donator.username %}">{{ item.donator }}</a></td>
            <td>{{ item.PICOIN }}</td>
            {% if item.where %}
            <td><a href="{% url 'photo:photo_detail' item.where.id %}">{{ item.where }}</a></td>
            {% else %}
            <td>충전</td>
            {% endif %}
            <td>{{ item.donate_dt }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

PICO_PROJECT/templates/profile.html
{% extends "base.html" %}
{% load sorl_thumbnail %}
{% load widget_tweaks %}
{% block title %}{{ profile.user.username }}{% endblock %}
{% block content %}

<header class="major">
    <h2>{{ profile.user.username }}</h2>
    <p>
        <strong> Followers: </strong> <a href="{% url 'followers' profile.user.username %}">{{ profile.followers.count }}</a>&nbsp;
        <strong> Following: </strong> <a href="{% url 'following' profile.user.username %}">{{ profile.following.count }}</a>
    </p>
    {% ifequal request.user.username profile.user.username %}
    <p>    
        <strong>Picoin : <a href="{% url 'mypicolog' user.get_username %}">{{ profile.PICOIN }}</a></strong> 
        <strong><a href="{% url 'charge' %}">+</a> </strong>      
    </p>
    {% endifequal %}
    <div>
        {% ifnotequal request.user profile.user %}
            {% if request.user in profile.followers.all %}
            <a href="{% url 'follow' profile.user.username %}" class="button">UnFollow</a>
            {% else %}
            <a href="{% url 'follow' profile.user.username %}" class="button">Follow</a>
            {% endif %}
        {% endifnotequal %}
    </div>
</header>
<section id="content">
{% ifnotequal request.user profile.user %}
<div class="row">
    {% for photo in photos %}
    <div class="col-md-3 mb-5">       
        <div class="tumbnail">
            <a href="{{ photo.get_absolute_url }}">
                {% thumbnail photo.image "128x128" crop="center" as im %}
                <img src="{{ im.url }}" style="width: 100%;">
                {% endthumbnail %}
            </a>
        </div>
        <ul>
            <li class="font-italic">{{ photo.title }}</li>
            <li class="font-italic">{{ photo.upload_dt|date:"Y-m-d" }}</li>
        </ul> 
    </div>
    {% endfor %}
</div> 
{% else %}
<div class="row gtr-150">
    <div class="col-4 col-12-medium">
        <section id="sidebar">
            <ul class="actions fit">
                <li><a href="{% url 'photo:photo_add' %}" class="button">Add Photo</a></li>        
            </ul>
            <ul class="actions fit">
                <li><a href="{% url 'password_change' %}" class="button">Change Password</a></li>        
            </ul>
        </section>
    </div>
    <div class="col-8 col-12-medium imp-medium">
            <section id="content">
                <div class="row">
                    {% for photo in photos %}
                    <div class="col-md-3 mb-5">       
                        <div class="tumbnail">
                            <a href="{{ photo.get_absolute_url }}">
                                {% thumbnail photo.image "128x128" crop="center" as im %}
                                <img src="{{ im.url }}" style="width: 100%;">
                                {% endthumbnail %}
                            </a>
                        </div>
                        <ul>
                            <li class="font-italic">{{ photo.title }}</li>
                            <li class="font-italic">{{ photo.upload_dt|date:"Y-m-d" }}</li>
                        </ul> 
                    </div>
                    {% endfor %}
                </div> 
            </section>

    </div>
</div>
{% endifnotequal %} 
</section>   
{% endblock %}

PICO_PROJECT/templates/profile_followers.html
{% extends "base.html" %}

{% block title %}{{ user.username }}-followers{% endblock %}
{% block content %}
<h1>{{ user.username }} Followers</h1>
{% for follower in followers_list %}
<div>
    <a href="{% url 'profile' follower.username %}">{{ follower.username }}</a>
</div>
{% endfor %}
{% endblock %}

PICO_PROJECT/templates/profile_following.html
{% extends "base.html" %}

{% block title %}{{ user.username }}-followers{% endblock %}
{% block content %}
<h1>{{ user.username }} Following</h1>
{% for following in following_list %}
<div>
    <a href="{% url 'profile' following.username %}">{{ following.username }}</a>
</div>
{% endfor %}
{% endblock %}

PICO_PROJECT/templates/search.html
{% extends "base.html" %}
{% block titile %}photo_search.html{% endblock %}
{% block content %}
{% if search %}
    {% if search_word %}
        {% ifequal search_word|slice:":1" "@" %}
            {% for user in search %}
                <a href="{% url 'profile' user.username %}">{{ user.username }}</a>
            {% endfor %}
        {% else %}
            {% for photo in search %}
                <h2><a href="{{ photo.get_absolute_url }}">{{ photo.title }}</a></h2>
                {{ photo.modify_date|date:"N d, Y" }}
                <p>{{ photo.description }}</p>
                <p>{{ photo.owner.username }}</p>
            {% endfor %}
        {% endifequal %}
    {% endif %}
    {% if search_words %}
        {% for photo in search %}
            <h2><a href="{{ photo.get_absolute_url }}">{{ photo.title }}</a></h2>
            {{ photo.modify_date|date:"N d, Y" }}
            <p>{{ photo.description }}</p>
            <p>{{ photo.owner.username }}</p>
        {% endfor %}
    {% endif %}
{% else %}
    {% if search_word %}
        <b><i>Search Word({{ search_word }}) Not Found!</i></b>
    {% elif search_words %}
        <b><i>Search Word({{ search_words }}) Not Found!</i></b>
    {% endif %}
{% endif %}
{% endblock %}