PICO_PROJECT/PICO_PROJECT/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from . import views
from core.views import ProfileView, ChargeView, MyPicoLog
from core.views import follow, FollowersView, FollowingView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', views.register, name='register'),
    re_path(r'^accounts/register/activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),

    path('', views.HomeView.as_view(), name='home'),
    path('explore/', include('photo.urls')),
    path('charge/', ChargeView.as_view(), name='charge'),
    path('search/', views.post_search, name='search'),
    path('log/user/<str:username>', MyPicoLog.as_view(), name='mypicolog'),
    # path('log/photo/<int:pk>', name='photopicolog'),
    path('<str:username>/', ProfileView.as_view(), name='profile'),
    path('<str:username>/follow/', follow, name='follow'),
    path('<str:username>/followers', FollowersView.as_view(), name='followers'),
    path('<str:username>/following', FollowingView.as_view(), name='following'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PICO_PROJECT/photo/urls.py
from django.urls import path
from . import views

app_name = 'photo'
urlpatterns = [
    # 기본 explore은 day의 rank와 같다.
    path('', views.PhotoLV.as_view(), name='index'),

    path('day', views.PhotoLVRankDay.as_view(), name='rank_day'),
    path('week/', views.PhotoLVRankWeek.as_view(), name='rank_week'),
    path('month/', views.PhotoLVRankMonth.as_view(), name='rank_month'),
    path('3month/', views.PhotoLVRank3Month.as_view(), name='rank_3month'),
    path('year/', views.PhotoLVRankYear.as_view(), name='rank_year'),
    path('all/', views.PhotoLVRankAll.as_view(), name='rank_all'),

    path('follow/', views.PhotoFollowView.as_view(), name='follow'),
    path('<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    path('add/', views.PhotoCV.as_view(), name='photo_add'),
    path('change/', views.PhotoChangeLV.as_view(), name='photo_change'),
    path('<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),
    path('<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),

    path('<int:pk>/donate', views.PhotoDonateDetailView.as_view(), name='photo_donate'),
    path('<int:pk>/log', views. PhotoPicoLog.as_view(), name='photo_pico_log'),

    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
] 

PICO_PROJECT/photo/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from taggit.managers import TaggableManager
# Create your models here.

class Photo(models.Model):
    title = models.CharField('TITLE', max_length=30)
    description = models.TextField('Photo Description', blank=True)
    tags = TaggableManager(blank=True)
    PICOIN = models.PositiveIntegerField(default=0, verbose_name='PICOIN')
    # image = ThumbnailImageField(upload_to='photo/%Y/%m')
    image = models.ImageField('IMAGE', upload_to='SorlPhoto/%Y')
    upload_dt = models.DateTimeField('Upload Date', auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

PICO_PROJECT/photo/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.contrib.auth.models import User
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from .models import Photo
from django.db import transaction
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render, Http404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DeleteView
from django.db.models import Q, Sum
from PICO_PROJECT.views import OwnerOnlyMixin, OtherOnlyMixin

from core.forms import DonateForm
from core.models import PhotoicoInfoLog, ProfilePicoInfoLog

from itertools import chain

# Create your views here.

# 랭크를 도입할때에는 사진에 붙은 로그를 참조해야합니다.
# 사진에 붙은 로그에서 후원된 날짜를 기준으로 하루, 주, 월, 3개월, 년을 체크해야합니다.
# 확인한 후, 포함이 되면 그 금액을 모두 더합니다.
# 더한 금액을 기준으로 하여 정렬을 해야합니다. 만약에 값이 같으면 먼저 업로드된 기준으로 정렬합니다.
# Entry.objects.filter(pub_date__lte='2006-01-01') => 2006년 1월 1일보다 작은 것을 찾는다. gt(e) 는 큰 것을 찾는다.
# Blog.objects.annotate(Count('entry')) annotate를 사용하면 집계가능
# Foo.objects.filter(datefield__date=datetime.date.today())
# Sample.objects.filter(date__range=["2011-01-01", "2011-01-31"])
# from datetime import datetime, timedelta
# Entry.objects.filter(pub_date__gte = datetime.now() - timedelta(days=1)) 

class PhotoLV(ListView):
    model = Photo

    def get_queryset(self):
        return Photo.objects.all().order_by('-upload_dt')

class PhotoLVRankDay(ListView):
    model = Photo
    template_name = 'photo/photo_list_rank.html'
    def get_context_data(self, **kwargs):
        context = super(PhotoLVRankDay, self).get_context_data(**kwargs)
        
        # 도네이션 된지 하루인 것 가져오기 
        infolog = PhotoicoInfoLog.objects.filter(donate_dt__gte=datetime.now()-relativedelta(days=1))

        # photo로 그룹을 묶어준다. 그 후, PICOIN을 SUM해준다.
        infolog = infolog.values('photo').annotate(total_PICO=Sum('PICOIN')).order_by('photo__id')
        
        photo_list = Photo.objects.filter(id__in=infolog.values_list('photo'))
        photo_list = list(zip(photo_list, infolog))
        
        photo_list = sorted(photo_list, key=lambda x:x[1]['total_PICO'], reverse=True)

        context['photo_list'] = photo_list

        return context

class PhotoLVRankWeek(ListView):
    model = Photo
    template_name = 'photo/photo_list_rank.html'
    def get_context_data(self, **kwargs):
        context = super(PhotoLVRankWeek, self).get_context_data(**kwargs)
        infolog = PhotoicoInfoLog.objects.filter(donate_dt__gte=datetime.now()-relativedelta(weeks=1))
        infolog = infolog.values('photo').annotate(total_PICO=Sum('PICOIN')).order_by('photo__id')
        
        photo_list = Photo.objects.filter(id__in=infolog.values_list('photo'))
        photo_list = list(zip(photo_list, infolog))
        photo_list = sorted(photo_list, key=lambda x:x[1]['total_PICO'], reverse=True)

        context['photo_list'] = photo_list

        return context

class PhotoLVRankMonth(ListView):
    model = Photo
    template_name = 'photo/photo_list_rank.html'
    def get_context_data(self, **kwargs):
        context = super(PhotoLVRankMonth, self).get_context_data(**kwargs)
        infolog = PhotoicoInfoLog.objects.filter(donate_dt__gte=datetime.now()-relativedelta(months=1))
        infolog = infolog.values('photo').annotate(total_PICO=Sum('PICOIN')).order_by('photo__id')
        
        photo_list = Photo.objects.filter(id__in=infolog.values_list('photo'))
        photo_list = list(zip(photo_list, infolog))
        
        photo_list = sorted(photo_list, key=lambda x:x[1]['total_PICO'], reverse=True)

        context['photo_list'] = photo_list

        return context

class PhotoLVRank3Month(ListView):
    model = Photo
    template_name = 'photo/photo_list_rank.html'
    def get_context_data(self, **kwargs):
        context = super(PhotoLVRank3Month, self).get_context_data(**kwargs)
        infolog = PhotoicoInfoLog.objects.filter(donate_dt__gte=datetime.now()-relativedelta(months=3))
        infolog = infolog.values('photo').annotate(total_PICO=Sum('PICOIN')).order_by('photo__id')
        
        photo_list = Photo.objects.filter(id__in=infolog.values_list('photo'))
        photo_list = list(zip(photo_list, infolog))
        
        photo_list = sorted(photo_list, key=lambda x:x[1]['total_PICO'], reverse=True)

        context['photo_list'] = photo_list

        return context

class PhotoLVRankYear(ListView):
    model = Photo
    template_name = 'photo/photo_list_rank.html'
    def get_context_data(self, **kwargs):
        context = super(PhotoLVRankYear, self).get_context_data(**kwargs)
        infolog = PhotoicoInfoLog.objects.filter(donate_dt__gte=datetime.now()-relativedelta(years=1))
        infolog = infolog.values('photo').annotate(total_PICO=Sum('PICOIN')).order_by('photo__id')
        
        photo_list = Photo.objects.filter(id__in=infolog.values_list('photo'))
        photo_list = list(zip(photo_list, infolog))
        
        photo_list = sorted(photo_list, key=lambda x:x[1]['total_PICO'], reverse=True)

        context['photo_list'] = photo_list

        return context

class PhotoLVRankAll(ListView):
    model = Photo

    def get_queryset(self):
        return Photo.objects.all().order_by('-PICOIN')

class PhotoFollowView(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photo_follow_list.html'
    def get_queryset(self):
        following = self.request.user.profile.following.all()
        following = chain(following, [self.request.user])
        return Photo.objects.filter(owner__in=following).order_by('-upload_dt')

class PhotoDV(DetailView):
    model = Photo

    def get_context_data(self, **kwargs):
        context = super(PhotoDV, self).get_context_data(**kwargs)
        
        piclog = PhotoicoInfoLog.objects.filter(photo=self.kwargs.get('pk'))
        piclog = piclog.values('donator').annotate(total_PICO=Sum('PICOIN')).order_by('donator')
        piclog = piclog.order_by('-total_PICO')[:5]

        user_list = User.objects.filter(id__in=piclog.values_list('donator'))
        user_list = zip(user_list, piclog)

        user_list = sorted(user_list, key=lambda x:x[1]['total_PICO'], reverse=True)

        context['donate_user_list'] = user_list
        
        return context

class PhotoCV(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ('title', 'image', 'description', 'tags')
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class PhotoChangeLV(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)

class PhotoUV(OwnerOnlyMixin, UpdateView):
    model = Photo
    fields = ('title', 'image', 'description')
    success_url = reverse_lazy('photo:index')

class PhotoDelV(OwnerOnlyMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:index')

class PhotoDonateDetailView(OtherOnlyMixin, DetailView):
    model = Photo
    template_name = 'photo/photo_donate.html'

    def get_context_data(self, **kwargs):
        context = super(PhotoDonateDetailView, self).get_context_data(**kwargs)
        context['form'] = DonateForm()
        return context

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        form = DonateForm(request.POST)
        if form.is_valid():
            if(request.user.profile.PICOIN < form.cleaned_data['PICOIN']):
                return redirect(reverse('charge'))

            self.object = self.get_object()
            donating = PhotoicoInfoLog()
            donating.donator = request.user
            donating.PICOIN = form.cleaned_data['PICOIN']
            donating.photo = self.object
            donating.save()

            request.user.profile.PICOIN -= form.cleaned_data['PICOIN']
            request.user.save()

            # 후원받는 사람 PICOIN늘리기
            self.object.owner.profile.PICOIN += form.cleaned_data['PICOIN']
            self.object.owner.save()

            # 후원 받은 사람 LOGGING
            charging = ProfilePicoInfoLog()
            charging.profile = self.object.owner.profile
            charging.donator = request.user
            charging.PICOIN = form.cleaned_data['PICOIN']
            charging.where = self.object
            charging.save()

            # 후원 한 사람 LOGGING
            charging = ProfilePicoInfoLog()
            charging.profile = request.user.profile
            charging.donator = self.object.owner
            charging.PICOIN = -form.cleaned_data['PICOIN']
            charging.where = self.object
            charging.save()

            # 사진 PICOIN늘리기
            self.object.PICOIN += form.cleaned_data['PICOIN']
            self.object.save()

            return redirect('photo:photo_detail', self.object.id)
        else:
            self.object = self.get_object()
            context = super(PhotoDonateDetailView, self).get_context_data(**kwargs)
            context['form'] = form
            return self.render_to_response(context=context)

class PhotoPicoLog(TemplateView):
    template_name = 'photo_donate_list.html'

    def get(self, request, pk):
        photo = None
        try:
            photo = Photo.objects.get(pk=pk)
        except:
            raise Http404()
        
        logging = PhotoicoInfoLog.objects.filter(photo=photo)

        return render(request, 'photo/photo_donate_list.html', {'object_list': logging, 'photo':photo})

class TaggedObjectLV(ListView):
    template_name = 'photo/taggit_photo_list.html'
    model = Photo

    def get_queryset(self):
        return Photo.objects.filter(Q(tags__name__icontains=self.kwargs.get('tag')))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context

PICO_PROJECT/photo/templates/photo/photo_change_list.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}photo_change_list.html{% endblock %}
{% block content %}
<h1>Photo Change - {{ user }}</h1>
<br>
<table class="table table-bordered table-condensed table-striped">
    <thead>
        <tr class="table-primary">
            <th>Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for item in object_list %}
        <tr class="table-secondary">
            <td>{{ item.title }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
            <td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

PICO_PROJECT/photo/templates/photo/photo_confirm_delete.html
{% extends "base.html" %}
{% block title %}photo_confirm_delete.html{% endblock %}
{% block content %}
<h1>Photo Delete</h1>
<br>
<form action="." method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}" ?</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm">
</form>
{% endblock %}

PICO_PROJECT/photo/templates/photo/photo_detail.html
{% extends "base.html" %}
{% load disqus_tags %}
{% block title %}photo_detail.html{% endblock %}
{% block content %}
<header class="major">
    <h2>{{ object.title }}</h2>
    <p><a href="{% url 'profile' object.owner.username %}">{{ object.owner.username }}</a></p>
    {% ifequal request.user.username object.owner.username %}
    <p><span>
        <a href="{% url 'photo:photo_update' object.id %}" class="button">Update</a>
        <a href="{% url 'photo:photo_delete' object.id %}" class="button">Delete</a>
    </span></p>
    {% endifequal %}
    {% ifnotequal request.user.username object.owner.username %}
    <p><a href="{% url 'photo:photo_donate' object.id %}" class="button primary">Donate</a></p>
    {% endifnotequal %}
</header>
<section id="content">
    <div class="col-12">
        <a href="{{ object.image.url }}">
            <span class="image fit">
                <img src="{{ object.image.url }}" sylte="width: 100%;">
            </span>
        </a>
    </div>
    <ul class="col-12">
        <li class="h5">Photo Description</li>
        {% if object.description %}
        <p>{{ object.description|linebreaks }}</p>
        {% else %}
        <p>{{ blank }}</p>
        {% endif %}
        <li class="h5">Date Uploaded</li>
        <p>{{ object.upload_dt }}</p>
        <li class="h5">PICOIN</li>
        <p><a href="{% url 'photo:photo_pico_log' object.id %}" class="button primary small">{{ object.PICOIN }}</a></p>
        {% if donate_user_list %}
        <li class="h5">RANK</li>
        <table>
            <tbody>
                {% for donate_user in donate_user_list %}
                <tr>
                    <td><a href="{% url 'profile' donate_user.0.username %}">{{ donate_user.0.username }}</a></td>
                    <td>{{ donate_user.1.total_PICO }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}   
        <li>
            <div>
                <b>TAGS</b><i class="fas fa-tag"></i>
                {% load taggit_templatetags2_tags %}
                {% get_tags_for_object object as "tags" %}
                {% for tag in tags %}
                <a href="{% url 'photo:tagged_object_list' tag.name %}">{{ tag.name }}</a>
                {% endfor %}
                &emsp;
            </div>
        
        </li>    
    </ul>
    <div>      
        {% disqus_show_comments %}
    </div>
</section>
{% endblock %}

PICO_PROJECT/photo/templates/photo/photo_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}photo_form.html{% endblock %}

{% block extra-style %}
<style type="text/css">
.filebox input {
	position: absolute;
	width: 1px;
	height: 1px;
	padding: 0;
	margin: -1px;
	overflow: hidden;
	clip:rect(0,0,0,0);
	border: 0;
}

.filebox label {
	display: inline-block;
	padding: .5em .75em;
	color: #999;
	font-size: inherit;
	line-height: normal;
	vertical-align: middle;
	background-color: #fdfdfd;
	cursor: pointer;
	border: 1px solid #ebebeb;
	border-bottom-color: #e2e2e2;
	border-radius: .25em;
}

/* named upload */
.filebox .upload-name {
	display: inline-block;
	padding: .5em .75em;
	font-size: inherit;
	font-family: inherit;
	line-height: normal;
	vertical-align: middle;
	background-color: #f5f5f5;
  border: 1px solid #ebebeb;
  border-bottom-color: #e2e2e2;
  border-radius: .25em;
  -webkit-appearance: none; /* 네이티브 외형 감추기 */
  -moz-appearance: none;
  appearance: none;
}

/* imaged preview */
.filebox .upload-display {
	margin-bottom: 5px;
}

@media(min-width: 768px) {
	.filebox .upload-display {
		display: inline-block;
		margin-right: 5px;
		margin-bottom: 0;
	}
}

.filebox .upload-thumb-wrap {
	display: inline-block;
	width: 360px;
	padding: 2px;
	vertical-align: middle;
	border: 1px solid #ddd;
	border-radius: 5px;
	background-color: #fff;
}

.filebox .upload-display img {
	display: block;
	max-width: 100%;
	width: 100%;
	height: auto;
}

.filebox.bs3-primary label {
  color: #fff;
  background-color: #337ab7;
	border-color: #2e6da4;
}
</style>
{% endblock %}
{% block extra-script%}
<script>
    $(document).ready(function(){
   var fileTarget = $('.filebox .upload-hidden');

    fileTarget.on('change', function(){
        if(window.FileReader){
            // 파일명 추출
            var filename = $(this)[0].files[0].name;
        } 

        else {
            // Old IE 파일명 추출
            var filename = $(this).val().split('/').pop().split('\\').pop();
        };

        $(this).siblings('.upload-name').val(filename);
    });

    //preview image 
    var imgTarget = $('.preview-image .upload-hidden');

    imgTarget.on('change', function(){
        var parent = $(this).parent();
        parent.children('.upload-display').remove();

        if(window.FileReader){
            //image 파일만
            if (!$(this)[0].files[0].type.match(/image\//)) return;
            
            var reader = new FileReader();
            reader.onload = function(e){
                var src = e.target.result;
                parent.prepend('<div class="upload-display"><div class="upload-thumb-wrap"><img src="'+src+'" class="upload-thumb"></div></div>');
            }
            reader.readAsDataURL($(this)[0].files[0]);
        }

        else {
            $(this)[0].select();
            $(this)[0].blur();
            var imgSrc = document.selection.createRange().text;
            parent.prepend('<div class="upload-display"><div class="upload-thumb-wrap"><img class="upload-thumb"></div></div>');

            var img = $(this).siblings('.upload-display').find('img');
            img[0].style.filter = "progid:DXImageTransform.Microsoft.AlphaImageLoader(enable='true',sizingMethod='scale',src=\""+imgSrc+"\")";        
        }
    });
});
</script>
{% endblock %}
{% block content%}
<header class="major">
    <h2>{{ request.user.username }}</h2>
    <p>
        <strong> Followers: </strong> <a href="{% url 'followers' request.user.username %}">{{ request.user.profile.followers.count }}</a>&nbsp;
        <strong> Following: </strong> <a href="{% url 'following' request.user.username %}">{{ request.user.profile.following.count }}</a>
    </p>
    <p>    
        <strong>Picoin : <a href="{% url 'mypicolog' request.user.username %}">{{ request.user.profile.PICOIN }}</a></strong> 
        <strong><a href="{% url 'charge' %}">+</a> </strong>      
    </p>
</header>
<section id="content">
    <div class="row gtr-150">
        <div class="col-4 col-12-medium">
            <section id="sidebar">
                <ul class="actions fit">
                    <li><a href="{% url 'photo:photo_add' %}" class="button">Add Photo</a></li>        
                </ul>
                <ul class="actions fit">
                    <li><a href="{% url 'password_change' %}" class="button">Change Password</a></li>        
                </ul>
            </section>
        </div>
        <div class="col-8 col-12-medium imp-medium">
            <section id="content">
                <header class="major">
                    <h4>Photo Create/Update</h4>
                    {% if form.errors %}
                    <p>{{ form.errors }}</p>
                    {% endif %}
                </header>
                {% if form.is_multipart %}
                <form enctype="multipart/form-data" action="." method="POST">
                {% else %}
                <form action="." method="POST" ></form>
                {% endif %}
                    {% csrf_token %}
                    <div class="form-group row">
                        {{ form.title|append_attr:"class:form-control"|append_attr:"placeholder:Title" }}
                    </div>
                    <div class="form-group row">
                        {{ form.image|append_attr:"class:form-control"|add_label_class:"col-form-label" }}
                        <div class="filebox bs3-primary preview-image ">
                            <input class="upload-name" value="파일선택" disabled="disabled" style="width: 200px;">
                            <label for="id_image">업로드</label> 
                            {{ form.image|add_class:"upload-hidden" }} 
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ form.description|append_attr:"class:form-control"|append_attr:"rows:3"|append_attr:"placeholder:Description" }}
                    </div>
                    <div class="form-group row">
                        {{ form.tags|append_attr:"class:form-control"|append_attr:"placeholder:Tags(Comma-Separated)" }}
                    </div>
                    <div>
                        <input type="submit" class="button primary">
                    </div>
                </form>
            </section>
        </div>
    </div>
</section>   
{% endblock %}

PICO_PROJECT/photo/templates/photo/photo_list.html
{% extends "base.html" %}
{% load sorl_thumbnail %}
{% block title %}photo_list.html{% endblock %}

{% block content %}
<div class="row gtr-150">
    <div class="col-4 col-12-medium">
        <section id="sidebar">
            <div class="col-6 col-12">
                <ul class="actions fit"><li><a href="{% url 'photo:index' %}" class="button">New</a></li></ul>
                <hr>
                <ul class="actions fit"><li><a href="{% url 'photo:rank_day' %}" class="button">Day</a></li></ul>
                <ul class="actions fit"><li><a href="{% url 'photo:rank_week' %}" class="button">Week</a></li></ul>
                <ul class="actions fit"><li><a href="{% url 'photo:rank_month' %}" class="button">Month</a></li></ul> 
                <ul class="actions fit"><li><a href="{% url 'photo:rank_3month' %}" class="button">3Month</a></li></ul>
                <ul class="actions fit"><li><a href="{% url 'photo:rank_year' %}" class="button">Year</a></li></ul>
                <ul class="actions fit"><li><a href="{% url 'photo:rank_all' %}" class="button">All</a></li></ul>
            </div>
        </section>
    </div>
    <div class="col-8 col-12-medium imp-medium">
        <section id="content">
            <div class="row">
                {% for photo in object_list %}
                <div>
                    <div class="tumbnail">
                        <a href="{{ photo.get_absolute_url }}">
                            {% thumbnail photo.image "128x128" crop="center" as im %}
                            <img src="{{ im.url }}" style="width: 100%;">
                            {% endthumbnail %}
                        </a>
                    </div>
                    <ul>
                        <li class="font-italic">{{ photo.title }}</li>
                        <li class="font-italic">{{ photo.upload_dt|date:"Y-m-d" }}</li>
                    </ul>
                </div>
                {% endfor %}
            </div> 
        </section>
    </div>
</div>
{% endblock %}

PICO_PROJECT/photo/templates/photo/photo_list_rank.html
{% extends "base.html" %}
{% load sorl_thumbnail %}
{% block title %}photo_list_rank.html{% endblock %}
{% block content %}
    
<div class="row gtr-150">
    <div class="col-4 col-12-medium">
        <section id="sidebar">
            <div class="col-6 col-12">
                <ul class="actions fit"><li><a href="{% url 'photo:index' %}" class="button">New</a></li></ul>
                <hr>
                <ul class="actions fit"><li><a href="{% url 'photo:rank_day' %}" class="button">Day</a></li></ul>
                <ul class="actions fit"><li><a href="{% url 'photo:rank_week' %}" class="button">Week</a></li></ul>
                <ul class="actions fit"><li><a href="{% url 'photo:rank_month' %}" class="button">Month</a></li></ul> 
                <ul class="actions fit"><li><a href="{% url 'photo:rank_3month' %}" class="button">3Month</a></li></ul>
                <ul class="actions fit"><li><a href="{% url 'photo:rank_year' %}" class="button">Year</a></li></ul>
                <ul class="actions fit"><li><a href="{% url 'photo:rank_all' %}" class="button">All</a></li></ul>
            </div>
        </section>
    </div>
    <div class="col-8 col-12-medium imp-medium">
        <section id="content">
            <div class="row">
                {% for photos in photo_list %}
                <div class="col-md-3 mb-5">
                    <div class="tumbnail">
                        <a href="{{ photos.0.get_absolute_url }}">
                            {% thumbnail photos.0.image "128x128" crop="center" as im %}
                            <img src="{{ im.url }}" style="width: 100%;">
                            {% endthumbnail %}
                        </a>
                    </div>
                    <ul>
                        <li class="font-italic">{{ photos.0.title }}</li>
                        <li class="font-italic">{{ photos.1.total_PICO }}</li>
                        <li class="font-italic">{{ photos.0.upload_dt|date:"Y-m-d" }}</li>
                    </ul>
                </div>
                {% endfor %}
            </div>
        </section>
    </div>
</div>
    
{% endblock %}